apiVersion: v1
kind: Service
metadata:
  name: mysql-tp2-service
spec:
  type: NodePort
  selector:
    app: mysql-tp2
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306